### PR TITLE
[Referral View Page]: Connect referral preview card to backend

### PR DESCRIPTION
**Pull request by kritisingh0114**
Connects referral preview card to backend

Preview card contains:
Job Title Name
Name of Referred
Email of Referred
Shortened description of the reason for the referral

### CODE REVIEW

**Review by meagan-dalton — COMMENTED** [review]
killing it, 

I would just get rid the tab feature which I think is lines 112 - 117  in the Profile file and then this is all good!

**Comment by kritisingh0114** [comment]
Updated! first try 😎

https://user-images.githubusercontent.com/90220396/144732653-cea301b7-cc43-4e9f-a5ce-93f90399f2fc.mp4

**Review by meagan-dalton — APPROVED** [review]
amazing!

**Review by rdonati — APPROVED** [review]
Looks good! 👍

**Pull request merged**
