### PR TITLE
[Referral Creation] - Description Page

### PR DESCRIPTION
**Pull request by kngai98**
Added the description page (second page) of the referral creation pop-up.

### CODE REVIEW

**Review by rdonati — APPROVED** [review]
Looks like it does what it's supposed to! Three little things though:

1. I'm not sure what handleSubmit is doing here.. seems like it can be removed to me
2. Same thing with the outermost div (with className='App'). I think it could be removed
2. Not a huge thing, but it would be good to use MUI components instead of plain html stuff

Looks good!

**Comment by kngai98** [comment]
> Looks like it does what it's supposed to! Three little things though:
> 
> 1. I'm not sure what handleSubmit is doing here.. seems like it can be removed to me
> 2. Same thing with the outermost div (with className='App'). I think it could be removed
> 3. Not a huge thing, but it would be good to use MUI components instead of plain html stuff
> 
> Looks good!

**Comment by kngai98** [comment]
Do you know why some of the checks didn't pass? @rdonati

**Comment by rdonati** [comment]
@kngai98 
Yeah its because the tests are annoyingly picky lol.
Screen Shot 2021-12-01 at 3 56 44 PM
If you click on the details for the failing test you can see the error messages. Just need to remove useState import and description assignment (in handleSubmit)

**Comment by kngai98** [comment]
That was it. lol.

**Pull request merged**
