### PR TITLE
Navbar fix

### PR DESCRIPTION
**Pull request by Danny123234**
Removed drop down from the Navbar and replaced it with a log out icon (that shows log out when hovering over for non tech savvy peoples) and added a direct link to the profile page button

### CODE REVIEW

**Review by rdonati — APPROVED** [review]
One of the most accessible PRs I've ever seen

I think some stuff will need to change with out new setup (i.e. no more profile page).. but we can make another pr to address that

**Review by meagan-dalton — COMMENTED** [review]
this looks good, should we get rid of home in the navbar since we now just redirect right to jobs?

**Comment by Danny123234** [comment]
working on a way to fix that the create job post button is not appearing until refresh

**Comment by Danny123234** [comment]
fixed it

**Review by meagan-dalton — APPROVED** [review]

**Pull request merged**
